
[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.remove-out.linux]
command = "rm"
args = ["-rf", "out"]

[tasks.remove-out.windows]
script_runner = "powershell"
script_extension = "ps1"
script = '''
Remove-Item -LiteralPath "out" -Force -Recurse -ErrorAction SilentlyContinue
'''

[tasks.build-release-windows-32.linux]
command = "cargo"
args = ["build", "--release", "--target", "i686-pc-windows-gnu"]

[tasks.build-release-windows-64.linux]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-gnu"]

[tasks.build-debug-windows-32.linux]
command = "cargo"
args = ["build", "--target", "i686-pc-windows-gnu"]

[tasks.build-debug-windows-64.linux]
command = "cargo"
args = ["build", "--target", "x86_64-pc-windows-gnu"]

[tasks.build-release-windows-32.windows]
command = "cargo"
args = ["build", "--release", "--target", "i686-pc-windows-msvc"]

[tasks.build-release-windows-64.windows]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-msvc"]

[tasks.build-debug-windows-32.windows]
command = "cargo"
args = ["build", "--target", "i686-pc-windows-msvc"]

[tasks.build-debug-windows-64.windows]
command = "cargo"
args = ["build", "--target", "x86_64-pc-windows-msvc"]

[tasks.debug]
run_task = { name = [
    "build-debug-windows-32",
    "build-debug-windows-64",
], parallel = true }

[tasks.release]
run_task = { name = [
    "build-release-windows-32",
    "build-release-windows-64",
], parallel = true }

[tasks.pack-to-zip.linux]
script = '''
mkdir -p out
cp target/i686-pc-windows-gnu/release/native_api.dll out/NativeApi_x32.dll
cp target/x86_64-pc-windows-gnu/release/native_api.dll out/NativeApi_x64.dll
cp Manifest.xml out/
zip -r -j out/NativeApi.zip out/NativeApi_x64.dll out/NativeApi_x32.dll out/Manifest.xml
'''

[tasks.pack-to-zip.windows]
script_runner = "powershell"
script_extension = "ps1"
script = '''
New-Item -ItemType Directory -Path out -Force -ErrorAction SilentlyContinue
cp target/i686-pc-windows-msvc/release/native_api.dll out/NativeApi_x32.dll
cp target/x86_64-pc-windows-msvc/release/native_api.dll out/NativeApi_x64.dll
cp Manifest.xml out/
Compress-Archive -DestinationPath out/NativeApi.zip -Path out/NativeApi_x64.dll, out/NativeApi_x32.dll, out/Manifest.xml -Force
'''

[tasks.pack]
dependencies = ["clean", "release", "remove-out", "pack-to-zip"]